### ISSUE TITLE
Broken link on 'Human-Readable IDs'

### ISSUE THREAD

**Issue by frytg** [straw-hat-team/adr#182]
https://straw-hat-team.github.io/adr/adrs/4860595695/README.html

The link "[_About Data vs. Information_](https://www.systems-thinking.org/dikw/dikw.htm)" leads to a spam website, likely due to an expired domain.

**Comment by yordis** [comment]
The broken internet 😭 thank you for reporting, this is one of my favorite page to visit ever!
